- name: Provision web-server
  hosts: front
  become: true
  tasks:
    - name: Nginx install
      ansible.builtin.apt:
        name: nginx
        state: present
    - name: Nginx run
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true


- name: Provision backend
  hosts: back
  become: true

  tasks:
    - name: Test
      ansible.builtin.debug:
        msg: "Just test print"

    - name: Install packages
      ansible.builtin.package:
        name:
          - atop
        state: present
      tags:
        - packages

    - name: Change config
      ansible.builtin.lineinfile:
        path: /usr/share/atop/atop.daily
        regexp: '^LOGINTERVAL=[0-9]*(.*)$'
        line: 'LOGINTERVAL={{ atop_log_interval }}'
      notify: atop restart

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Start and enable atop
      ansible.builtin.systemd:
        name: atop
        state: started
        enabled: true

    - name: Install additional packages
      ansible.builtin.package:
        name: nano
        state: present
      tags:
        - packages

    - name: Any block name
      block:
        - name: Do something
          ansible.builtin.command: /usr/local/bin/do_something
          changed_when: false
      rescue:
        - name: Rescue debug
          ansible.builtin.debug:
            msg: "Failed, running rollback"
      always:
        - name: Always debug
          ansible.builtin.debug:
            msg: "Always done"

  handlers:
    - name: Atop restart
      ansible.builtin.service:
        name: atop
        state: restarted
        daemon_reload: true
